feat: validation-space-only
utfprapps-pb/portal-centro-analises-front pull request #10
Opened 2023-04-25 23:46 UTC by GiovaneWerlang

# Description

-Validação de campo caso seja preenchido apenas com espaços

# Fixes

- add a list of issues fixed by this PR

# Screenshot (optional)

2023-04-26 22:34 UTC, Minozzzi requested changes

2023-04-26 22:34 UTC, Minozzzi commented on src/validation/validators/spaceOnlyValidation.ts
> +    if (value.trim().length !== 0) return null
Talvez faça sentido colocar essa regra no `requiredFieldValidation` o que acha?

Ficaria algo como 
```ts
import { RequiredFieldError } from '../errors'
import { FieldValidation } from '../protocols'

export class RequiredFieldValidation implements FieldValidation {
  constructor(readonly field: string) {}

  validate(input: object): Error | null {
    const [, value] =
      Object.entries(input).find(([fieldName]) => fieldName === this.field) ||
      []

    if (value && !!value.trim()) return null

    return new RequiredFieldError()
  }
}

```

2023-04-26 22:34 UTC, Minozzzi commented
Boa ideia de validação, realmente tinha passado em branco essa questão!!

2023-04-29 22:09 UTC, GiovaneWerlang commented on src/validation/validators/spaceOnlyValidation.ts
> +    if (value.trim().length !== 0) return null
Faz sentido sim.

2023-05-02 16:40 UTC, Minozzzi approved these changes

2023-05-02 16:40 UTC, merged