Basic interface
utfprapps-pb/portal-centro-analises-front pull request #12
Opened 2023-04-27 00:54 UTC by leomoreno8

# Description

- Layout Básico apenas para ter uma noção. Alterações e melhorias em próximos PR.

# Fixes

- 

# Screenshot (optional)
![image](https://user-images.githubusercontent.com/62400571/234732482-73c1e778-64af-433d-bab0-8b61a3ebb680.png)

2023-04-27 01:41 UTC, Minozzzi requested changes

2023-04-27 01:41 UTC, Minozzzi commented on src/components/header/index.tsx
> +    <h2>Seja bem vindo, Leonardo</h2>
Adicionar um todo para deixar isso dinâmico, criar tarefa para retornar nome do usuário no back e ajustar essa questão no front. Algo como 

```ts
// ToDo @leomoreno8: {{sua-mensagem}}
```

2023-04-27 01:41 UTC, Minozzzi commented on src/components/header/styles.ts
> +const theme = {
Tem funções para responsividades padrão no theme do projeto, faz mais sentido usar aquelas, pois assim fica padronizado para todo o sistema. O que acha?
Da uma olhada 
https://github.com/utfprapps-pb/portal-centro-analises-front/blob/cade3d3aac3adaf1a0c71d41747353f4c4731bff/src/styles/themes/default.theme.ts#L46-L89

2023-04-27 01:41 UTC, Minozzzi commented on src/components/header/styles.ts
> +  padding: 1rem 2rem;
Usar `px`para espaçamento

2023-04-27 01:41 UTC, Minozzzi commented on src/components/header/styles.ts
> +    font-size: 0.7rem;
Usar `px`por padrão para unidades de medida

2023-04-27 01:41 UTC, Minozzzi commented on src/components/header/styles.ts
> +    font-size: 1rem;
Usar `px`por padrão para unidades de medida

2023-04-27 01:41 UTC, Minozzzi commented on src/components/header/styles.ts
> +      font-size: 1rem;
Usar `px`por padrão para unidades de medida

2023-04-27 01:41 UTC, Minozzzi commented on src/components/menu/styles.ts
> +const theme = {
Mesma questão para o header

2023-04-27 01:41 UTC, Minozzzi commented on src/components/menu/index.tsx
> +      <a href="/">
Faz mais sentido passar esses valores por prop, assim deixa mais dinâmico, o que acha?

2023-04-27 01:41 UTC, Minozzzi commented on src/styles/themes/theme.type.ts
> +    sm: Interpolation<
Não entendi o motivo desse tipo 🤔

2023-04-27 11:38 UTC, Minozzzi commented on src/components/header/styles.ts
> +    font-size: 1rem;
E para font-size temos também os valores padrões no theme do projeto

2023-04-27 11:38 UTC, Minozzzi commented on src/components/header/styles.ts
> +      font-size: 1rem;
E para font-size temos também os valores padrões no theme do projeto

2023-04-27 11:52 UTC, Minozzzi commented
Daria também para dentro da folder `routes` criar um arquivo menu.tsx
Que ficaria assim
`menu.tsx`:

```tsx

// pode crirar esse type no component de menu, arquivo types.ts
type item = {
  label: string
  icon: React.ReactNode
  path: string
}

export const menuItems = ObjectFreeze<item[]>([
{}, // seu item
{}, // ...
])

```

E então na folder `layouts` poderia criar um arquivo privateRouteProxy.tsx
Que ficaria assim
`privateRouteProxy.tsx`:
```tsx
// estilo principal
const Main = styled.main`
	width: 100vw;
	height: 100vh;

	display: grid;
	grid-template-columns: 320px 1fr;
	grid-template-rows: 80px 1fr;
	grid-template-areas:
		'Sidebar Header'
		'Sidebar Content';
`

type PrivateRouteProxyProps = PropsWithChidren

export const PrivateRouteProxy: React.FC<PrivateRouteProxyProps> = () => {
  const { auth, handleSignOut } = useAuth()

	const headerItems = useMemo<PopoverItemProps[]>(
		() => [
			{
				icon: <UserCircle size={22} />,
				text: 'Perfil',
				onClick: () => alert('Under Construction')
			},
			{
				icon: <SignOut size={22} />,
				text: 'Sair',
				onClick: handleSignOut
			}
		],
		[handleSignOut]
	)

	if (auth?.token)
		return (
			<Main>
				<Sidebar menuItems={menuItems} />
				<Header items={headerItems} />
                                 // esse cara pode ser um outro component na pasta layouts, que seria bem simples, vou colocar a baixo
				<LoggedUserContainer>{children}</LoggedUserContainer>
			</Main>
		)

	return <Navigate to={ROUTES.login.path()} />
} 
```

Exemplo do LoggedUserContainer:
```tsx


export const Content = styled.section`
	grid-area: Content;
	padding: ${sg.spacing.xxxlarge};
	overflow-y: auto;
`


export const LoggedUserContainer: React.FC<LoggedUserContainerProps> = ({
	children
}) => {
	return <S.Content>{children}</S.Content>
}

```


e por fim no Routes, você renderiza o PrivateRouteProxy por fora dos components de page. 

Essas alterações fazem sentido pra você? Qualquer coisa nós podemos trocar uma ideia

2023-05-02 22:37 UTC, leomoreno8 commented on src/styles/themes/theme.type.ts
> +    sm: Interpolation<
Também não, isso deve ter sido adicionado em algum quickfix do vscode, não escrevi. Removi

2023-05-02 22:38 UTC, leomoreno8 commented on src/components/header/styles.ts
> +      font-size: 1rem;
Troquei para px. Não vou criar componentes com 4 arquivos, passar como props e fazer todo aquele trampo se eu posso colocar um font-size: 14px.

2023-05-02 22:40 UTC, leomoreno8 commented on src/components/header/styles.ts
> +    font-size: 1rem;
Respondi no outro

2023-05-02 22:41 UTC, leomoreno8 commented on src/components/header/styles.ts
> +const theme = {
A definição dos padrões não foi acordado com ninguém. Vou deixar assim por enquanto.

2023-05-02 22:43 UTC, leomoreno8 commented on src/components/header/index.tsx
> +    <h2>Seja bem vindo, Leonardo</h2>
Coloquei

2023-05-02 22:44 UTC, leomoreno8 commented on src/components/header/styles.ts
> +    font-size: 0.7rem;
Feito

2023-05-02 22:44 UTC, leomoreno8 commented on src/components/menu/index.tsx
> +      <a href="/">
Discordo.

2023-05-02 22:51 UTC, leomoreno8 commented
> Daria também para dentro da folder `routes` criar um arquivo menu.tsx Que ficaria assim `menu.tsx`:
> 
> ```tsx
> // pode crirar esse type no component de menu, arquivo types.ts
> type item = {
>   label: string
>   icon: React.ReactNode
>   path: string
> }
> 
> export const menuItems = ObjectFreeze<item[]>([
> {}, // seu item
> {}, // ...
> ])
> ```
> 
> E então na folder `layouts` poderia criar um arquivo privateRouteProxy.tsx Que ficaria assim `privateRouteProxy.tsx`:
> 
> ```tsx
> // estilo principal
> const Main = styled.main`
> 	width: 100vw;
> 	height: 100vh;
> 
> 	display: grid;
> 	grid-template-columns: 320px 1fr;
> 	grid-template-rows: 80px 1fr;
> 	grid-template-areas:
> 		'Sidebar Header'
> 		'Sidebar Content';
> `
> 
> type PrivateRouteProxyProps = PropsWithChidren
> 
> export const PrivateRouteProxy: React.FC<PrivateRouteProxyProps> = () => {
>   const { auth, handleSignOut } = useAuth()
> 
> 	const headerItems = useMemo<PopoverItemProps[]>(
> 		() => [
> 			{
> 				icon: <UserCircle size={22} />,
> 				text: 'Perfil',
> 				onClick: () => alert('Under Construction')
> 			},
> 			{
> 				icon: <SignOut size={22} />,
> 				text: 'Sair',
> 				onClick: handleSignOut
> 			}
> 		],
> 		[handleSignOut]
> 	)
> 
> 	if (auth?.token)
> 		return (
> 			<Main>
> 				<Sidebar menuItems={menuItems} />
> 				<Header items={headerItems} />
>                                  // esse cara pode ser um outro component na pasta layouts, que seria bem simples, vou colocar a baixo
> 				<LoggedUserContainer>{children}</LoggedUserContainer>
> 			</Main>
> 		)
> 
> 	return <Navigate to={ROUTES.login.path()} />
> } 
> ```
> 
> Exemplo do LoggedUserContainer:
> 
> ```tsx
> export const Content = styled.section`
> 	grid-area: Content;
> 	padding: ${sg.spacing.xxxlarge};
> 	overflow-y: auto;
> `
> 
> 
> export const LoggedUserContainer: React.FC<LoggedUserContainerProps> = ({
> 	children
> }) => {
> 	return <S.Content>{children}</S.Content>
> }
> ```
> 
> e por fim no Routes, você renderiza o PrivateRouteProxy por fora dos components de page.
> 
> Essas alterações fazem sentido pra você? Qualquer coisa nós podemos trocar uma ideia

Sim, podemos conversar amanhã. Mas acho que aí vai em outra branch/PR

2023-05-02 23:30 UTC, Minozzzi commented
Cara, de boa, vi aqui que não vai ser feito algumas das coisas que eu sugeri e não tem um argumento plausível, os padrões estão definidos no arquivo `src/styles/themes/default.theme.ts`. Caso não vá de encontro com o padrão que você gosta de usar é super sugerível alterações nesse arquivo via PR.

Irei esse PR para ficar de acordo com a necessidade do projeto. Ai abro outro PR para essa feature

2023-05-02 23:53 UTC, Minozzzi commented
@leomoreno8 ok, pode da merge do PR. Depois corrigimos o que for necessário

2023-05-02 23:54 UTC, Minozzzi approved these changes

2023-05-02 23:55 UTC, Minozzzi approved these changes

2023-05-03 00:20 UTC, Falchizao commented on src/components/menu/index.tsx
> +      <a href="/">
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK

2023-05-03 00:54 UTC, Falchizao approved these changes
good

2023-05-03 00:54 UTC, merged

2023-05-03 00:56 UTC, Falchizao commented
boa pessoal! vamo que vamo