Route and container login
utfprapps-pb/portal-centro-analises-front pull request #4
Opened 2023-04-12 22:03 UTC by marco-rozo

# Description

Fixes # 
https://trello.com/c/DNb8l5Cl/10-front-cria%C3%A7%C3%A3o-das-rotas

# Screenshot 
![alt text](https://imgur.com/nFY9dez)

2023-04-12 23:41 UTC, Minozzzi requested changes

2023-04-12 23:41 UTC, Minozzzi commented on package.json
> +    "phosphor-react": "^1.4.1",
A gente ta usando icons do material ui para manter padronizado com os components, faz sentido usar essa?

2023-04-12 23:41 UTC, Minozzzi commented on src/main.tsx
> +        {/* <AuthProvider> */}
Remover comentários

2023-04-17 22:27 UTC, marco-rozo commented
ok

2023-04-18 16:07 UTC, Minozzzi approved these changes

2023-04-18 17:24 UTC, viniciuspegorini approved these changes
ok!

2023-04-18 23:14 UTC, merged