feat: component checkbox
utfprapps-pb/portal-centro-analises-front pull request #8
Opened 2023-04-23 15:56 UTC by GiovaneWerlang

# Description

- add component checkbox

2023-04-25 22:28 UTC, Minozzzi requested changes
Exportar o componente no file `components/inputs/index.ts`

2023-04-25 22:31 UTC, Minozzzi requested changes

2023-04-25 22:31 UTC, Minozzzi commented on src/components/inputs/formControlLabel/types.ts
> +export type FormControlLabelProps = PropsWithChildren<Props>
Acho que o nome do type poderia ser `CheckboxProps`para padronizar o nome do componente. O mesmo vale para o nome da pasta

2023-04-26 22:27 UTC, Minozzzi requested changes
Precisa do componente `formControlLabel`? 
Acho que da para excluir essa pasta, ta idêntico ao componente `checkbox`

2023-05-02 16:41 UTC, Minozzzi approved these changes

2023-05-02 23:35 UTC, Minozzzi approved these changes

2023-05-03 14:38 UTC, Falchizao approved these changes
lgtm!

2023-05-03 14:44 UTC, merged