Develop historico feat
utfprapps-pb/portal-centro-analises-front pull request #93
Opened 2023-11-29 22:51 UTC by GiovaneWerlang

# Description

- Adição de uma dialog que permite ao admin alterar o status da solicitação através da tela de histórico.

# Fixes

- add a list of issues fixed by this PR

# Screenshot (optional)

2023-11-29 23:11 UTC, erickeliasborges submitted a review, later dismissed
OK.

2023-12-05 23:08 UTC, felipemaccari requested changes

2023-12-05 23:08 UTC, felipemaccari commented on src/components/historico/index.tsx
> +                      url={'teste'}
aqui a url vai ficar teste mesmo?

2023-12-05 23:22 UTC, GiovaneWerlang commented on src/components/historico/index.tsx
> +                      url={'teste'}
não, reverti a alteração

2023-12-05 23:24 UTC, felipemaccari approved these changes

2023-12-05 23:24 UTC, merged